services:

    infinitescroll:
        class: Gesdinet\InfiniteScrollBundle\InfiniteScroll
        arguments: [ '@logger', '@validator' ]

    Gesdinet\InfiniteScrollBundle\InfiniteScrollInterface: '@infinitescroll'
